name: After release package

env:
  develop_branch: "develop"

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  tests:
    needs: build
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        include:
          - customer: "John"
            configuration: {
              version: "3.12",
              repo: "repo/John",
              branch: $develop_branch
            }
          - customer: "Elie"
            configuration: {
              version: "3.11",
              repo: "repo/Elie",
              branch: "release/1.23"
            }
          - customer: "Doug"
            configuration: {
              version: "3.9",
              repo: "repo/Doug",
              branch: $develop_branch
            }
          - customer: "Zoe"
            configuration: {
              version: "3.11",
              repo: "repo/Zoe",
              branch: "main"
            }

    steps:
      - name: Released ${{github.event.release.tag_name}}
        if: ${{ startsWith(github.event.release.tag_name, matrix.configuration.version) }}
        run: echo "release ${{github.event.release.tag_name}} for ${{matrix.customer}} on repo ${{matrix.configuration.repo}} branch ${{matrix.configuration.branch}}"

