name: Create release package

on: 
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+*', '[0-9]+.[0-9]+.[0-9]+.[0-9]+*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x

      - name: Publish
        run: dotnet publish ./src/WebApplication.sln -c Release -o ../public

      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          path: ./public
          filename: 'release.${{github.ref_name}}.zip'

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release.${{github.ref_name}}.zip
