name: Get ref on push

on:
  workflow_dispatch:
    inputs:
      checkout-ref:
        description: Branch, tag or Sha used for checkout
        required: false
        type: string
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+', '[0-9]+.[0-9]+.[0-9]+-alpha[0-9]+']
    branches:
      - main

env:
  used-ref: ${{ github.event.inputs.checkout-ref && github.ref_name }}

jobs:
  get-ref:
    runs-on: ubuntu-latest
    steps:
      - name: set_output
        id: setOutput
        run: echo "${{ env.used-ref }}"
