name: Multiple triggers variable handling

on: 
  workflow_dispatch:
    inputs:
      release_name:
        description: Tag of Github release that you want to trigger this workflow for
        required: true
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  set_release_tag:
    runs-on: ubuntu-latest
    steps:
      - name: from_release
        if: github.event.release
        run: echo "tag=${{github.event.release.tag_name}}" >> $GITHUB_ENV
      - name: from_workflow_dispatch
        if: github.event.inputs
        run: echo "tag=${{github.event.inputs.release_name}}" >> $GITHUB_ENV
      - name: show_tag
        run: echo "tag=${{env.tag}}"
